name: "python_environment"
description: "Ensures that venv is set up and python deps are installed"
runs:
  using: "composite"
  steps:
    - name: Hash requirements.txt
      run: echo "cache_key=requirements_txt_2_$(shasum -a 256 requirements.txt | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
      shell: bash
      id: hash

    - name: Cache venv
      id: cache-venv
      uses: actions/cache@v4
      with:
        path: venv
        key: ${{ steps.hash.outputs.cache_key }}

    - name: Create venv
      run: virtualenv venv
      shell: bash
      if: steps.cache-venv.outputs.cache-hit != 'true'

    - name: Activate venv
      run: |
        source venv/bin/activate
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        which python
        du -h venv
      shell: bash

    - name: Install requirements
      run: pip3 install -r requirements.txt
      shell: bash
      if: steps.cache-venv.outputs.cache-hit != 'true'
