# fly.toml app configuration file generated for urbanstats-ci-proxy on 2025-05-16T21:06:45-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'urbanstats-ci-proxy'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8001
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2G'
  cpu_kind = 'performance'
  cpus = 1

[mounts]
  source = "densitydb"
  destination = "densitydb"
