name: "docker_image"
description: "Based on a Dockerfile hash, checks if an image exists, if not, builds and pushes it"
inputs:
  dockerfile:
    description: "Path to the Dockerfile"
    required: true
  repository:
    description: "The docker respository"
    required: false
    default: ${{ github.repository }}/dockerfile-hash
  registry:
    description: "The docker registry"
    required: false
    default: ghcr.io
  token:
    description: "The Github token to access ghcr"
    required: true
outputs:
  image:
    description: "The fully qualified image generated"
    value: ${{ steps.image.outputs.image }}
runs:
  using: "composite"
  steps:
    - name: Create the tag by hashing the dockerfile
      id: tag
      run: echo "tag=$(shasum -a 256 ${{ inputs.dockerfile }} | cut -d ' ' -f 1)" >> $GITHUB_OUTPUT
      shell: bash

    - name: concat the Docker image name
      id: image
      run: echo "image=${{ inputs.registry }}/${{ inputs.repository }}:${{ steps.tag.outputs.tag }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Check for existing image
      id: existing-image
      run: |
        GHCR_TOKEN=$(echo -n ${{ inputs.token }} | base64)
        echo "response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${GHCR_TOKEN}" https://${{ inputs.registry }}/v2/${{ inputs.repository }}/manifests/${{ steps.tag.outputs.tag }})" >> $GITHUB_OUTPUT
      shell: bash

    - name: Log in to the Container registry
      if: ${{ steps.existing-image.outputs.response == '404' }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push Docker image
      if: ${{ steps.existing-image.outputs.response == '404' }}
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.image.outputs.image }}
