from urbanstats.acs.load import ACSDataEntity


entities = dict(
    education=ACSDataEntity(
        "EDUCATIONAL ATTAINMENT FOR THE POPULATION 25 YEARS AND OVER",
        "population_18",
        "block group",
        {
            "education_total": ["Estimate!!Total:"],
            "education_no": [
                "Estimate!!Total:!!No schooling completed",
                "Estimate!!Total:!!Nursery school",
                "Estimate!!Total:!!Kindergarten",
                "Estimate!!Total:!!1st grade",
                "Estimate!!Total:!!2nd grade",
                "Estimate!!Total:!!3rd grade",
                "Estimate!!Total:!!4th grade",
                "Estimate!!Total:!!5th grade",
                "Estimate!!Total:!!6th grade",
                "Estimate!!Total:!!7th grade",
                "Estimate!!Total:!!8th grade",
                "Estimate!!Total:!!9th grade",
                "Estimate!!Total:!!10th grade",
                "Estimate!!Total:!!11th grade",
                "Estimate!!Total:!!12th grade, no diploma",
            ],
            "education_high_school": [
                "Estimate!!Total:!!Regular high school diploma",
                "Estimate!!Total:!!GED or alternative credential",
                "Estimate!!Total:!!GED or alternative credential",
                "Estimate!!Total:!!Some college, less than 1 year",
                "Estimate!!Total:!!Some college, 1 or more years, no degree",
                "Estimate!!Total:!!Associate's degree",
            ],
            "education_ugrad": [
                "Estimate!!Total:!!Bachelor's degree",
            ],
            "education_grad": [
                "Estimate!!Total:!!Master's degree",
                "Estimate!!Total:!!Professional school degree",
                "Estimate!!Total:!!Doctorate degree",
            ],
        },
    ),
    education_field=ACSDataEntity(
        "FIELD OF BACHELOR'S DEGREE FOR FIRST MAJOR FOR THE POPULATION 25 YEARS AND OVER",
        "population_18",
        "block group",
        {
            "education_field_total": ["Estimate!!Total:"],
            "education_field_stem": [
                "Estimate!!Total:!!Science and Engineering Related Fields",
                "Estimate!!Total:!!Science and Engineering",
            ],
            "education_field_humanities": [
                "Estimate!!Total:!!Arts, Humanities and Other",
                "Estimate!!Total:!!Education",
            ],
            "education_field_business": [
                "Estimate!!Total:!!Business",
            ],
        },
    ),
    generation=ACSDataEntity(
        # collected in 2021, so generations are =, and we are using []
        # silent (1928-1945) = 76-93 [75, inf] which is [-inf, 1946]
        # boomer (1946-1964) = 57-75 [55, 74] which is [1946, 1966]
        # genx (1965-1980) = 41-56 [40, 54] which is [1967, 1981]
        # millenial (1981-1996) = 25-40 [25, 39] which is [1982, 1996]
        # genz (1997-2012) = 9-24 [10, 24] which is [1997, 2011]
        # genalpha (2013-2025) = 0-8 [0, 9] which is [2012, 2021]
        "SEX BY AGE",
        "population",
        "block group",
        {
            "generation_total": [
                "Estimate!!Total:",
            ],
            "generation_silent": [
                # 75+
                "Estimate!!Total:!!Male:!!75 to 79 years",
                "Estimate!!Total:!!Male:!!80 to 84 years",
                "Estimate!!Total:!!Male:!!85 years and over",
                "Estimate!!Total:!!Female:!!75 to 79 years",
                "Estimate!!Total:!!Female:!!80 to 84 years",
                "Estimate!!Total:!!Female:!!85 years and over",
            ],
            "generation_boomer": [
                # 55-74
                "Estimate!!Total:!!Male:!!55 to 59 years",
                "Estimate!!Total:!!Male:!!60 and 61 years",
                "Estimate!!Total:!!Male:!!62 to 64 years",
                "Estimate!!Total:!!Male:!!65 and 66 years",
                "Estimate!!Total:!!Male:!!67 to 69 years",
                "Estimate!!Total:!!Male:!!70 to 74 years",
                "Estimate!!Total:!!Female:!!55 to 59 years",
                "Estimate!!Total:!!Female:!!60 and 61 years",
                "Estimate!!Total:!!Female:!!62 to 64 years",
                "Estimate!!Total:!!Female:!!65 and 66 years",
                "Estimate!!Total:!!Female:!!67 to 69 years",
                "Estimate!!Total:!!Female:!!70 to 74 years",
            ],
            "generation_genx": [
                # 40-54
                "Estimate!!Total:!!Male:!!40 to 44 years",
                "Estimate!!Total:!!Male:!!45 to 49 years",
                "Estimate!!Total:!!Male:!!50 to 54 years",
                "Estimate!!Total:!!Female:!!40 to 44 years",
                "Estimate!!Total:!!Female:!!45 to 49 years",
                "Estimate!!Total:!!Female:!!50 to 54 years",
            ],
            "generation_millenial": [
                # 25-39
                "Estimate!!Total:!!Male:!!25 to 29 years",
                "Estimate!!Total:!!Male:!!30 to 34 years",
                "Estimate!!Total:!!Male:!!35 to 39 years",
                "Estimate!!Total:!!Female:!!25 to 29 years",
                "Estimate!!Total:!!Female:!!30 to 34 years",
                "Estimate!!Total:!!Female:!!35 to 39 years",
            ],
            "generation_genz": [
                # 10-24
                "Estimate!!Total:!!Male:!!10 to 14 years",
                "Estimate!!Total:!!Male:!!15 to 17 years",
                "Estimate!!Total:!!Male:!!18 and 19 years",
                "Estimate!!Total:!!Male:!!20 years",
                "Estimate!!Total:!!Male:!!21 years",
                "Estimate!!Total:!!Male:!!22 to 24 years",
                "Estimate!!Total:!!Female:!!10 to 14 years",
                "Estimate!!Total:!!Female:!!15 to 17 years",
                "Estimate!!Total:!!Female:!!18 and 19 years",
                "Estimate!!Total:!!Female:!!20 years",
                "Estimate!!Total:!!Female:!!21 years",
                "Estimate!!Total:!!Female:!!22 to 24 years",
            ],
            "generation_genalpha": [
                # 0-9
                "Estimate!!Total:!!Male:!!Under 5 years",
                "Estimate!!Total:!!Male:!!5 to 9 years",
                "Estimate!!Total:!!Female:!!Under 5 years",
                "Estimate!!Total:!!Female:!!5 to 9 years",
            ],
            None: [
                "Estimate!!Total:!!Female:",
                "Estimate!!Total:!!Male:",
            ],
        },
    ),
    household_income=ACSDataEntity(
        "TENURE BY HOUSEHOLD INCOME IN THE PAST 12 MONTHS (IN 2021 INFLATION-ADJUSTED DOLLARS)",
        "occupied",
        "tract",
        {
            "household_income_under_50k": [
                "Estimate!!Total:!!Owner occupied:!!Less than $5,000",
                "Estimate!!Total:!!Owner occupied:!!$5,000 to $9,999",
                "Estimate!!Total:!!Owner occupied:!!$10,000 to $14,999",
                "Estimate!!Total:!!Owner occupied:!!$15,000 to $19,999",
                "Estimate!!Total:!!Owner occupied:!!$20,000 to $24,999",
                "Estimate!!Total:!!Owner occupied:!!$25,000 to $34,999",
                "Estimate!!Total:!!Owner occupied:!!$35,000 to $49,999",
                "Estimate!!Total:!!Renter occupied:!!Less than $5,000",
                "Estimate!!Total:!!Renter occupied:!!$5,000 to $9,999",
                "Estimate!!Total:!!Renter occupied:!!$10,000 to $14,999",
                "Estimate!!Total:!!Renter occupied:!!$15,000 to $19,999",
                "Estimate!!Total:!!Renter occupied:!!$20,000 to $24,999",
                "Estimate!!Total:!!Renter occupied:!!$25,000 to $34,999",
                "Estimate!!Total:!!Renter occupied:!!$35,000 to $49,999",
            ],
            "household_income_50k_to_100k": [
                "Estimate!!Total:!!Renter occupied:!!$50,000 to $74,999",
                "Estimate!!Total:!!Renter occupied:!!$75,000 to $99,999",
                "Estimate!!Total:!!Owner occupied:!!$50,000 to $74,999",
                "Estimate!!Total:!!Owner occupied:!!$75,000 to $99,999",
            ],
            "household_income_over_100k": [
                "Estimate!!Total:!!Renter occupied:!!$100,000 to $149,999",
                "Estimate!!Total:!!Renter occupied:!!$150,000 or more",
                "Estimate!!Total:!!Owner occupied:!!$100,000 to $149,999",
                "Estimate!!Total:!!Owner occupied:!!$150,000 or more",
            ],
            None: [
                "Estimate!!Total:",
                "Estimate!!Total:!!Owner occupied:",
                "Estimate!!Total:!!Renter occupied:",
            ],
        },
    ),
    personal_income=ACSDataEntity(
        "SEX BY WORK EXPERIENCE IN THE PAST 12 MONTHS BY INCOME IN THE PAST 12 MONTHS (IN 2021 INFLATION-ADJUSTED DOLLARS) FOR THE POPULATION 15 YEARS AND OVER",
        "population_18",
        "tract",
        {
            None: [
                "Estimate!!Total:",
                "Estimate!!Total:!!Female:",
                "Estimate!!Total:!!Female:!!Other:",
                "Estimate!!Total:!!Female:!!Other:!!No income",
                "Estimate!!Total:!!Female:!!Other:!!With income:",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!No income",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:",
                "Estimate!!Total:!!Male:",
                "Estimate!!Total:!!Male:!!Other:",
                "Estimate!!Total:!!Male:!!Other:!!No income",
                "Estimate!!Total:!!Male:!!Other:!!With income:",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!No income",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:",
            ],
            "individual_income_under_50k": [
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$1 to $2,499 or loss",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$10,000 to $12,499",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$12,500 to $14,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$15,000 to $17,499",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$17,500 to $19,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$2,500 to $4,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$20,000 to $22,499",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$22,500 to $24,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$25,000 to $29,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$30,000 to $34,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$35,000 to $39,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$40,000 to $44,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$45,000 to $49,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$5,000 to $7,499",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$7,500 to $9,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$1 to $2,499 or loss",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$10,000 to $12,499",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$12,500 to $14,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$15,000 to $17,499",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$17,500 to $19,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$2,500 to $4,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$20,000 to $22,499",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$22,500 to $24,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$25,000 to $29,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$30,000 to $34,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$35,000 to $39,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$40,000 to $44,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$45,000 to $49,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$5,000 to $7,499",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$7,500 to $9,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$1 to $2,499 or loss",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$10,000 to $12,499",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$12,500 to $14,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$15,000 to $17,499",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$17,500 to $19,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$2,500 to $4,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$20,000 to $22,499",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$22,500 to $24,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$25,000 to $29,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$30,000 to $34,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$35,000 to $39,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$40,000 to $44,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$45,000 to $49,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$5,000 to $7,499",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$7,500 to $9,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$1 to $2,499 or loss",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$10,000 to $12,499",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$12,500 to $14,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$15,000 to $17,499",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$17,500 to $19,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$2,500 to $4,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$20,000 to $22,499",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$22,500 to $24,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$25,000 to $29,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$30,000 to $34,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$35,000 to $39,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$40,000 to $44,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$45,000 to $49,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$5,000 to $7,499",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$7,500 to $9,999",
            ],
            "individual_income_50k_to_100k": [
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$50,000 to $54,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$55,000 to $64,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$65,000 to $74,999",
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$75,000 to $99,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$50,000 to $54,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$55,000 to $64,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$65,000 to $74,999",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$75,000 to $99,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$50,000 to $54,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$55,000 to $64,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$65,000 to $74,999",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$75,000 to $99,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$50,000 to $54,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$55,000 to $64,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$65,000 to $74,999",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$75,000 to $99,999",
            ],
            "individual_income_over_100k": [
                "Estimate!!Total:!!Female:!!Other:!!With income:!!$100,000 or more",
                "Estimate!!Total:!!Female:!!Worked full-time, year-round in the past 12 months:!!With income:!!$100,000 or more",
                "Estimate!!Total:!!Male:!!Other:!!With income:!!$100,000 or more",
                "Estimate!!Total:!!Male:!!Worked full-time, year-round in the past 12 months:!!With income:!!$100,000 or more",
            ],
        },
    ),
    # aggregate_income_total=ACSDataEntity(
    #     "AGGREGATE INCOME IN THE PAST 12 MONTHS (IN 2021 INFLATION-ADJUSTED DOLLARS)",
    #     "population_18",
    #     "block group",
    #     {
    #         "aggregate_income_total": [
    #             "Estimate!!Aggregate income in the past 12 months (in 2021 inflation-adjusted dollars)"
    #         ]
    #     },
    #     replace_negatives_with_nan=True,
    # ),
    # aggregate_income_capital=ACSDataEntity(
    #     "AGGREGATE INTEREST, DIVIDENDS, OR NET RENTAL INCOME IN THE PAST 12 MONTHS (IN 2021 INFLATION-ADJUSTED DOLLARS) FOR HOUSEHOLDS",
    #     "population_18",
    #     "block group",
    #     {
    #         "aggregate_income_capital": [
    #             "Estimate!!Aggregate interest, dividends, or net rental income in the past 12 months (in 2021 inflation-adjusted dollars)"
    #         ]
    #     },
    #     replace_negatives_with_nan=True,
    # ),
    # aggregate_income_labor=ACSDataEntity(
    #     "AGGREGATE WAGE OR SALARY INCOME IN THE PAST 12 MONTHS (IN 2021 INFLATION-ADJUSTED DOLLARS) FOR HOUSEHOLDS",
    #     "population_18",
    #     "block group",
    #     {
    #         "aggregate_income_labor": [
    #             "Estimate!!Aggregate wage or salary income in the past 12 months (in 2021 inflation-adjusted dollars)"
    #         ]
    #     },
    #     replace_negatives_with_nan=True,
    # ),
    transportation_means=ACSDataEntity(
        "MEANS OF TRANSPORTATION TO WORK",
        "population_18",
        "block group",
        {
            "transportation_means_car": [
                "Estimate!!Total:!!Car, truck, or van:",
                "Estimate!!Total:!!Taxicab",
            ],
            "transportation_means_bike": [
                "Estimate!!Total:!!Bicycle",
                "Estimate!!Total:!!Motorcycle",
            ],
            "transportation_means_walk": [
                "Estimate!!Total:!!Walked",
            ],
            "transportation_means_transit": [
                "Estimate!!Total:!!Public transportation (excluding taxicab):",
            ],
            "transportation_means_worked_at_home": [
                "Estimate!!Total:!!Worked from home",
            ],
            "transportation_means_other": [
                "Estimate!!Total:!!Other means",
            ],
            None: [
                "Estimate!!Total:",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-person carpool",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 4-person carpool",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 5- or 6-person carpool",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 7-or-more-person carpool",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Ferryboat",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Light rail, streetcar or trolley (carro público in Puerto Rico)",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail",
            ],
        },
    ),
    transportation_commute_time=ACSDataEntity(
        "MEANS OF TRANSPORTATION TO WORK BY TRAVEL TIME TO WORK",
        "population_18",
        "block group",
        {
            "transportation_commute_time_under_15": [
                "Estimate!!Total:!!Less than 10 minutes",
                "Estimate!!Total:!!10 to 14 minutes",
            ],
            "transportation_commute_time_15_to_29": [
                "Estimate!!Total:!!15 to 19 minutes",
                "Estimate!!Total:!!20 to 24 minutes",
                "Estimate!!Total:!!25 to 29 minutes",
            ],
            "transportation_commute_time_30_to_59": [
                "Estimate!!Total:!!30 to 34 minutes",
                "Estimate!!Total:!!35 to 44 minutes",
                "Estimate!!Total:!!45 to 59 minutes",
            ],
            "transportation_commute_time_over_60": [
                "Estimate!!Total:!!60 or more minutes",
            ],
            None: [
                "Estimate!!Total:",
                "Estimate!!Total:!!Car, truck, or van:",
                "Estimate!!Total:!!Car, truck, or van:!!10 to 14 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!15 to 19 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!20 to 24 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!25 to 29 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!30 to 34 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!35 to 44 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!45 to 59 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!60 or more minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!10 to 14 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!15 to 19 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!20 to 24 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!25 to 29 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!30 to 34 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!35 to 44 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!45 to 59 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!60 or more minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!10 to 14 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!15 to 19 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!20 to 24 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!25 to 29 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!30 to 34 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!35 to 44 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!45 to 59 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!60 or more minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 2-person carpool:!!Less than 10 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!10 to 14 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!15 to 19 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!20 to 24 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!25 to 29 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!30 to 34 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!35 to 44 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!45 to 59 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!60 or more minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!In 3-or-more-person carpool:!!Less than 10 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Carpooled:!!Less than 10 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!10 to 14 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!15 to 19 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!20 to 24 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!25 to 29 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!30 to 34 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!35 to 44 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!45 to 59 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!60 or more minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Drove alone:!!Less than 10 minutes",
                "Estimate!!Total:!!Car, truck, or van:!!Less than 10 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!10 to 14 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!15 to 19 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!20 to 24 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!25 to 29 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!30 to 34 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!35 to 44 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!45 to 59 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!60 or more minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!10 to 14 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!15 to 19 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!20 to 24 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!25 to 29 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!30 to 34 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!35 to 44 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!45 to 59 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!60 or more minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Bus:!!Less than 10 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Less than 10 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!10 to 14 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!15 to 19 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!20 to 24 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!25 to 29 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!30 to 34 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!35 to 44 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!45 to 59 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!60 or more minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Long-distance train or commuter rail or Ferryboat:!!Less than 10 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!10 to 14 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!15 to 19 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!20 to 24 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!25 to 29 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!30 to 34 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!35 to 44 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!45 to 59 minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!60 or more minutes",
                "Estimate!!Total:!!Public transportation (excluding taxicab):!!Subway or elevated rail, Light rail, streetcar, or trolley (carro público in Puerto Rico):!!Less than 10 minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!10 to 14 minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!15 to 19 minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!20 to 24 minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!25 to 29 minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!30 to 34 minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!35 to 44 minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!45 to 59 minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!60 or more minutes",
                "Estimate!!Total:!!Taxicab, motorcycle, bicycle, or other means:!!Less than 10 minutes",
                "Estimate!!Total:!!Walked:",
                "Estimate!!Total:!!Walked:!!10 to 14 minutes",
                "Estimate!!Total:!!Walked:!!15 to 19 minutes",
                "Estimate!!Total:!!Walked:!!20 to 24 minutes",
                "Estimate!!Total:!!Walked:!!25 to 29 minutes",
                "Estimate!!Total:!!Walked:!!30 to 34 minutes",
                "Estimate!!Total:!!Walked:!!35 to 44 minutes",
                "Estimate!!Total:!!Walked:!!45 to 59 minutes",
                "Estimate!!Total:!!Walked:!!60 or more minutes",
                "Estimate!!Total:!!Walked:!!Less than 10 minutes",
            ],
        },
    ),
    rent=ACSDataEntity(
        "BEDROOMS BY GROSS RENT",
        "occupied",
        "block group",
        {
            "rent_1br_under_750": [
                "Estimate!!Total:!!1 bedroom:!!With cash rent:!!Less than $300",
                "Estimate!!Total:!!1 bedroom:!!With cash rent:!!$300 to $499",
                "Estimate!!Total:!!1 bedroom:!!With cash rent:!!$500 to $749",
            ],
            "rent_1br_750_to_1500": [
                "Estimate!!Total:!!1 bedroom:!!With cash rent:!!$750 to $999",
                "Estimate!!Total:!!1 bedroom:!!With cash rent:!!$1,000 to $1,499",
            ],
            "rent_1br_over_1500": [
                "Estimate!!Total:!!1 bedroom:!!With cash rent:!!$1,500 or more",
            ],
            "rent_2br_under_750": [
                "Estimate!!Total:!!2 bedrooms:!!With cash rent:!!Less than $300",
                "Estimate!!Total:!!2 bedrooms:!!With cash rent:!!$300 to $499",
                "Estimate!!Total:!!2 bedrooms:!!With cash rent:!!$500 to $749",
            ],
            "rent_2br_750_to_1500": [
                "Estimate!!Total:!!2 bedrooms:!!With cash rent:!!$750 to $999",
                "Estimate!!Total:!!2 bedrooms:!!With cash rent:!!$1,000 to $1,499",
            ],
            "rent_2br_over_1500": [
                "Estimate!!Total:!!2 bedrooms:!!With cash rent:!!$1,500 or more",
            ],
            "rent_with_cash_rent": [
                "Estimate!!Total:!!1 bedroom:!!With cash rent:",
                "Estimate!!Total:!!2 bedrooms:!!With cash rent:",
                "Estimate!!Total:!!3 or more bedrooms:!!With cash rent:",
                "Estimate!!Total:!!No bedroom:!!With cash rent:",
            ],
            None: [
                "Estimate!!Total:",
                "Estimate!!Total:!!1 bedroom:",
                "Estimate!!Total:!!2 bedrooms:!!No cash rent",
                "Estimate!!Total:!!2 bedrooms:",
                "Estimate!!Total:!!1 bedroom:!!No cash rent",
                "Estimate!!Total:!!3 or more bedrooms:",
                "Estimate!!Total:!!3 or more bedrooms:!!No cash rent",
                "Estimate!!Total:!!3 or more bedrooms:!!With cash rent:!!$1,000 to $1,499",
                "Estimate!!Total:!!3 or more bedrooms:!!With cash rent:!!$1,500 or more",
                "Estimate!!Total:!!3 or more bedrooms:!!With cash rent:!!$300 to $499",
                "Estimate!!Total:!!3 or more bedrooms:!!With cash rent:!!$500 to $749",
                "Estimate!!Total:!!3 or more bedrooms:!!With cash rent:!!$750 to $999",
                "Estimate!!Total:!!3 or more bedrooms:!!With cash rent:!!Less than $300",
                "Estimate!!Total:!!No bedroom:",
                "Estimate!!Total:!!No bedroom:!!No cash rent",
                "Estimate!!Total:!!No bedroom:!!With cash rent:!!$1,000 to $1,499",
                "Estimate!!Total:!!No bedroom:!!With cash rent:!!$1,500 or more",
                "Estimate!!Total:!!No bedroom:!!With cash rent:!!$300 to $499",
                "Estimate!!Total:!!No bedroom:!!With cash rent:!!$500 to $749",
                "Estimate!!Total:!!No bedroom:!!With cash rent:!!$750 to $999",
                "Estimate!!Total:!!No bedroom:!!With cash rent:!!Less than $300",
            ],
        },
    ),
    # aggregate_rent=ACSDataEntity(
    #     "AGGREGATE GROSS RENT (DOLLARS)",
    #     "occupied",
    #     "block group",
    #     {"aggregate_rent": ["Estimate!!Aggregate gross rent"]},
    #     replace_negatives_with_nan=True,
    # ),
    # internet_access=ACSDataEntity(
    #     "INTERNET SUBSCRIPTIONS IN HOUSEHOLD",
    #     "occupied",
    #     {}
    # )
)

acs_columns = [column for entity in entities.values() for column in entity.categories]
