categories = {
    "Agriculture, forestry, fishing and hunting, and mining": {
        # Custom categories
        "Agriculture": [
            "Estimate!!Total!!Crop production",
            "Estimate!!Total!!Animal production and aquaculture",
        ],
        "Forestry, fishing, and hunting": [
            "Estimate!!Total!!Forestry except logging",
            "Estimate!!Total!!Logging",
            "Estimate!!Total!!Fishing, hunting and trapping",
            "Estimate!!Total!!Support activities for agriculture and forestry",
        ],
    },
    "Mining, quarrying, and oil and gas extraction": [
        "Estimate!!Total!!Oil and gas extraction",
        "Estimate!!Total!!Coal mining",
        "Estimate!!Total!!Metal ore mining",
        "Estimate!!Total!!Nonmetallic mineral mining and quarrying",
        "Estimate!!Total!!Support activities for mining",
    ],
    "Construction": [
        "Estimate!!Total!!Construction (the cleaning of buildings and dwellings is incidental during construction and immediately after construction)",
    ],
    "Manufacturing": [
        "Estimate!!Total!!Animal food, grain and oilseed milling",
        "Estimate!!Total!!Sugar and confectionery products",
        "Estimate!!Total!!Fruit and vegetable preserving and specialty food manufacturing",
        "Estimate!!Total!!Dairy product manufacturing",
        "Estimate!!Total!!Animal slaughtering and processing",
        "Estimate!!Total!!Retail bakeries",
        "Estimate!!Total!!Bakeries and tortilla manufacturing, except retail bakeries",
        "Estimate!!Total!!Seafood and other miscellaneous foods, n.e.c.",
        "Estimate!!Total!!Not specified food industries",
        "Estimate!!Total!!Beverage manufacturing",
        "Estimate!!Total!!Tobacco manufacturing",
        "Estimate!!Total!!Fiber, yarn, and thread mills",
        "Estimate!!Total!!Fabric mills, except knitting mills",
        "Estimate!!Total!!Textile and fabric finishing and fabric coating mills",
        "Estimate!!Total!!Carpet and rug mills",
        "Estimate!!Total!!Textile product mills, except carpet and rug",
        "Estimate!!Total!!Knitting fabric mills, and apparel knitting mills",
        "Estimate!!Total!!Cut and sew, and apparel accessories and other apparel manufacturing",
        "Estimate!!Total!!Footwear manufacturing",
        "Estimate!!Total!!Leather and hide tanning and finishing, and other leather and allied product manufacturing",
        "Estimate!!Total!!Pulp, paper, and paperboard mills",
        "Estimate!!Total!!Paperboard container manufacturing",
        "Estimate!!Total!!Miscellaneous paper and pulp products",
        "Estimate!!Total!!Printing and related support activities",
        "Estimate!!Total!!Petroleum refining",
        "Estimate!!Total!!Miscellaneous petroleum and coal products",
        "Estimate!!Total!!Resin, synthetic rubber, and fibers and filaments manufacturing",
        "Estimate!!Total!!Agricultural chemical manufacturing",
        "Estimate!!Total!!Pharmaceutical and medicine manufacturing",
        "Estimate!!Total!!Paint, coating, and adhesive manufacturing",
        "Estimate!!Total!!Soap, cleaning compound, and cosmetics manufacturing",
        "Estimate!!Total!!Industrial and miscellaneous chemicals",
        "Estimate!!Total!!Plastics product manufacturing",
        "Estimate!!Total!!Tire manufacturing",
        "Estimate!!Total!!Rubber products, except tires, manufacturing",
        "Estimate!!Total!!Pottery, ceramics, and plumbing fixture manufacturing",
        "Estimate!!Total!!Clay building material and refractories manufacturing",
        "Estimate!!Total!!Glass and glass product manufacturing",
        "Estimate!!Total!!Cement, concrete, lime, and gypsum product manufacturing",
        "Estimate!!Total!!Miscellaneous nonmetallic mineral product manufacturing",
        "Estimate!!Total!!Iron and steel mills and steel product manufacturing",
        "Estimate!!Total!!Aluminum production and processing",
        "Estimate!!Total!!Nonferrous metal (except aluminum) production and processing",
        "Estimate!!Total!!Foundries",
        "Estimate!!Total!!Metal forgings and stampings",
        "Estimate!!Total!!Cutlery and hand tool manufacturing",
        "Estimate!!Total!!Structural metals, and boiler, tank, and shipping container manufacturing",
        "Estimate!!Total!!Machine shops; turned product; screw, nut, and bolt manufacturing",
        "Estimate!!Total!!Coating, engraving, heat treating, and allied activities",
        "Estimate!!Total!!Ordnance",
        "Estimate!!Total!!Miscellaneous fabricated metal products manufacturing",
        "Estimate!!Total!!Not specified metal industries",
        "Estimate!!Total!!Agricultural implement manufacturing",
        "Estimate!!Total!!Construction, and mining and oil and gas field machinery manufacturing",
        "Estimate!!Total!!Commercial and service industry machinery manufacturing",
        "Estimate!!Total!!Metalworking machinery manufacturing",
        "Estimate!!Total!!Engine, turbine, and power transmission equipment manufacturing",
        "Estimate!!Total!!Machinery manufacturing, n.e.c. or not specified",
        "Estimate!!Total!!Computer and peripheral equipment manufacturing",
        "Estimate!!Total!!Communications, audio, and video equipment manufacturing",
        "Estimate!!Total!!Navigational, measuring, electromedical, and control instruments manufacturing",
        "Estimate!!Total!!Electronic component and product manufacturing, n.e.c.",
        "Estimate!!Total!!Household appliance manufacturing",
        "Estimate!!Total!!Electric lighting and electrical equipment manufacturing, and other electrical component manufacturing, n.e.c.",
        "Estimate!!Total!!Motor vehicles and motor vehicle equipment manufacturing",
        "Estimate!!Total!!Aircraft and parts manufacturing",
        "Estimate!!Total!!Aerospace products and parts manufacturing",
        "Estimate!!Total!!Railroad rolling stock manufacturing",
        "Estimate!!Total!!Ship and boat building",
        "Estimate!!Total!!Other transportation equipment manufacturing",
        "Estimate!!Total!!Sawmills and wood preservation",
        "Estimate!!Total!!Veneer, plywood, and engineered wood products",
        "Estimate!!Total!!Prefabricated wood buildings and mobile homes manufacturing",
        "Estimate!!Total!!Miscellaneous wood products",
        "Estimate!!Total!!Furniture and related product manufacturing",
        "Estimate!!Total!!Medical equipment and supplies manufacturing",
        "Estimate!!Total!!Sporting and athletic goods, and doll, toy and game manufacturing",
        "Estimate!!Total!!Miscellaneous manufacturing, n.e.c.",
        "Estimate!!Total!!Not specified manufacturing industries",
    ],
    "Wholesale and retail trade": {
        "Wholesale trade": [
            "Estimate!!Total!!Motor vehicle and motor vehicle parts and supplies merchant wholesalers",
            "Estimate!!Total!!Furniture and home furnishing merchant wholesalers",
            "Estimate!!Total!!Lumber and other construction materials merchant wholesalers",
            "Estimate!!Total!!Professional and commercial equipment and supplies merchant wholesalers",
            "Estimate!!Total!!Metals and minerals, except petroleum, merchant wholesalers",
            "Estimate!!Total!!Household appliances and electrical and electronic goods merchant wholesalers",
            "Estimate!!Total!!Hardware, and plumbing and heating equipment, and supplies merchant wholesalers",
            "Estimate!!Total!!Machinery, equipment, and supplies merchant wholesalers",
            "Estimate!!Total!!Recyclable material merchant wholesalers",
            "Estimate!!Total!!Miscellaneous durable goods merchant wholesalers",
            "Estimate!!Total!!Paper and paper products merchant wholesalers",
            "Estimate!!Total!!Drugs, sundries, and chemical and allied products merchant  wholesalers",
            "Estimate!!Total!!Apparel, piece goods, and notions merchant wholesalers",
            "Estimate!!Total!!Grocery and related product merchant wholesalers",
            "Estimate!!Total!!Farm product raw material merchant wholesalers",
            "Estimate!!Total!!Petroleum and petroleum products merchant wholesalers",
            "Estimate!!Total!!Alcoholic beverages merchant wholesalers",
            "Estimate!!Total!!Farm supplies merchant wholesalers",
            "Estimate!!Total!!Miscellaneous nondurable goods merchant wholesalers",
            "Estimate!!Total!!Wholesale electronic markets and agents and brokers",
            "Estimate!!Total!!Not specified wholesale trade",
        ],
        "Retail trade": [
            "Estimate!!Total!!Automobile dealers",
            "Estimate!!Total!!Other motor vehicle dealers",
            "Estimate!!Total!!Automotive parts, accessories, and tire stores",
            "Estimate!!Total!!Furniture and home furnishings stores",
            "Estimate!!Total!!Household appliance stores",
            "Estimate!!Total!!Electronics Stores",
            "Estimate!!Total!!Building material and supplies dealers",
            "Estimate!!Total!!Hardware stores",
            "Estimate!!Total!!Lawn and garden equipment and supplies stores",
            "Estimate!!Total!!Supermarkets and other grocery (except convenience) stores",
            "Estimate!!Total!!Convenience Stores",
            "Estimate!!Total!!Specialty food stores",
            "Estimate!!Total!!Beer, wine, and liquor stores",
            "Estimate!!Total!!Pharmacies and drug stores",
            "Estimate!!Total!!Health and personal care, except drug, stores",
            "Estimate!!Total!!Gasoline stations",
            "Estimate!!Total!!Clothing stores",
            "Estimate!!Total!!Shoe stores",
            "Estimate!!Total!!Jewelry, luggage, and leather goods stores",
            "Estimate!!Total!!Sporting goods, and hobby and toy stores",
            "Estimate!!Total!!Sewing, needlework, and piece goods stores",
            "Estimate!!Total!!Musical instrument and supplies stores",
            "Estimate!!Total!!Book stores and news dealers",
            "Estimate!!Total!!Department stores",
            "Estimate!!Total!!General merchandise stores, including warehouse clubs and supercenters",
            "Estimate!!Total!!Florists",
            "Estimate!!Total!!Office supplies and stationery stores",
            "Estimate!!Total!!Used merchandise stores",
            "Estimate!!Total!!Gift, novelty, and souvenir shops",
            "Estimate!!Total!!Miscellaneous retail stores",
            "Estimate!!Total!!Electronic shopping and mail-order houses",
            "Estimate!!Total!!Vending machine operators",
            "Estimate!!Total!!Fuel dealers",
            "Estimate!!Total!!Other direct selling establishments",
            "Estimate!!Total!!Not specified retail trade",
        ],
    },
    "Transportation and utilities": {
        "Transportation and warehousing": [
            "Estimate!!Total!!Air transportation",
            "Estimate!!Total!!Rail transportation",
            "Estimate!!Total!!Water transportation",
            "Estimate!!Total!!Truck transportation",
            "Estimate!!Total!!Bus service and urban transit",
            "Estimate!!Total!!Taxi and limousine service",
            "Estimate!!Total!!Pipeline transportation",
            "Estimate!!Total!!Scenic and sightseeing transportation",
            "Estimate!!Total!!Services incidental to transportation",
            "Estimate!!Total!!Postal Service",
            "Estimate!!Total!!Couriers and messengers",
            "Estimate!!Total!!Warehousing and storage",
        ],
        "Utilities": [
            "Estimate!!Total!!Electric power generation, transmission and distribution",
            "Estimate!!Total!!Natural gas distribution",
            "Estimate!!Total!!Electric and gas, and other combinations",
            "Estimate!!Total!!Water, steam, air-conditioning, and irrigation systems",
            "Estimate!!Total!!Sewage treatment facilities",
            "Estimate!!Total!!Not specified utilities",
        ],
    },
    "Financial activities": [
        "Estimate!!Total!!Banking and related activities",
        "Estimate!!Total!!Savings institutions, including credit unions",
        "Estimate!!Total!!Nondepository credit and related activities",
        "Estimate!!Total!!Securities, commodities, funds, trusts, and other financial investments",
        "Estimate!!Total!!Insurance carriers",
        "Estimate!!Total!!Agencies, brokerages, and other insurance related activities",
        "Estimate!!Total!!Lessors of real estate, and offices of real estate agents and brokers",
        "Estimate!!Total!!Real estate property managers, offices of real estate appraisers, and other activities related to real estate",
        "Estimate!!Total!!Automotive equipment rental and leasing",
        "Estimate!!Total!!Other consumer goods rental",
        "Estimate!!Total!!Commercial, industrial, and other intangible assets rental and leasing",
    ],
    "Education and health services": {
        "Educational services": [
            "Estimate!!Total!!Elementary and secondary schools",
            "Estimate!!Total!!Colleges, universities, and professional schools, including junior colleges",
            "Estimate!!Total!!Business, technical, and trade schools and training",
            "Estimate!!Total!!Other schools and instruction, and educational support services",
        ],
        "Health care and social assistance": [
            "Estimate!!Total!!Offices of physicians",
            "Estimate!!Total!!Offices of dentists",
            "Estimate!!Total!!Offices of chiropractors",
            "Estimate!!Total!!Offices of optometrists",
            "Estimate!!Total!!Offices of other health practitioners",
            "Estimate!!Total!!Outpatient care centers",
            "Estimate!!Total!!Home health care services",
            "Estimate!!Total!!Other health care services",
            "Estimate!!Total!!General medical and surgical hospitals, and specialty (except psychiatric and substance abuse) hospitals",
            "Estimate!!Total!!Psychiatric and substance abuse hospitals",
            "Estimate!!Total!!Nursing care facilities (skilled nursing facilities)",
            "Estimate!!Total!!Residential care facilities, except skilled nursing facilities",
            "Estimate!!Total!!Individual and family services",
            "Estimate!!Total!!Community food and housing, and emergency services",
            "Estimate!!Total!!Vocational rehabilitation services",
            "Estimate!!Total!!Child day care services",
        ],
    },
    "Leisure and hospitality": {
        "Estimate!!Total!!Performing arts companies",
        "Estimate!!Total!!Spectator sports",
        "Estimate!!Total!!Promoters of performing arts, sports, and similar events, agents and managers for artists, athletes, entertainers, and other public figures",
        "Estimate!!Total!!Independent artists, writers, and performers",
        "Estimate!!Total!!Museums, art galleries, historical sites, and similar institutions",
        "Estimate!!Total!!Bowling centers",
        "Estimate!!Total!!Other amusement, gambling, and recreation industries",
        "Estimate!!Total!!Traveler accommodation",
        "Estimate!!Total!!Recreational vehicle parks and camps, and rooming and boarding houses, dormitories, and workers' camps",
        "Estimate!!Total!!Restaurants and other food services",
        "Estimate!!Total!!Drinking places, alcoholic beverages",
    },
    "Public administration": [
        "Estimate!!Total!!Executive offices and legislative bodies",
        "Estimate!!Total!!Public finance activities",
        "Estimate!!Total!!Other general government and support",
        "Estimate!!Total!!Justice, public order, and safety activities",
        "Estimate!!Total!!Administration of human resource programs",
        "Estimate!!Total!!Administration of environmental quality and housing programs",
        "Estimate!!Total!!Administration of economic programs and space research",
        "Estimate!!Total!!National security and international affairs",
    ],
    "Information": {
        # custom
        "Technology": [
            "Estimate!!Total!!Software publishers",
            "Estimate!!Total!!Internet publishing and broadcasting and web search portals",
            "Estimate!!Total!!Wired telecommunications carriers",
            "Estimate!!Total!!Telecommunications, except wired telecommunications carriers",
            "Estimate!!Total!!Data processing, hosting, and related services",
        ],
        "Information except technology": [
            "Estimate!!Total!!Newspaper publishers",
            "Estimate!!Total!!Periodical, book, and directory publishers",
            "Estimate!!Total!!Motion pictures and video industries",
            "Estimate!!Total!!Sound recording industries",
            "Estimate!!Total!!Broadcasting (except internet)",
            "Estimate!!Total!!Libraries and archives",
            "Estimate!!Total!!Other information services, except libraries and archives, and internet publishing and broadcasting and web search portals",
        ],
    },
}

{
    "Agriculture": categories["Agriculture, forestry, fishing and hunting, and mining"][
        "Agriculture"
    ],
    "Forestry, fishing, and hunting": categories[
        "Agriculture, forestry, fishing and hunting, and mining"
    ]["Forestry, fishing, and hunting"],
    "Mining, quarrying, and oil and gas extraction": categories[
        "Mining, quarrying, and oil and gas extraction"
    ],
    "Construction": categories["Construction"],
    "Manufacturing": categories["Manufacturing"],
    "Wholesale trade": categories["Wholesale and retail trade"]["Wholesale trade"],
    "Retail trade": categories["Wholesale and retail trade"]["Retail trade"],
    "Transportation and warehousing": categories["Transportation and utilities"][
        "Transportation and warehousing"
    ],
    "Utilities": categories["Transportation and utilities"]["Utilities"],
    "Financial activities": categories["Financial activities"],
    "Educational services": categories["Education and health services"][
        "Educational services"
    ],
    "Health care and social assistance": categories["Education and health services"][
        "Health care and social assistance"
    ],
    "Leisure and hospitality except restaurants": [
        x
        for x in categories["Leisure and hospitality"]
        if x != "Estimate!!Total!!Restaurants and other food services"
    ],
    "Restaurants and other food services": [
        "Estimate!!Total!!Restaurants and other food services"
    ],
    "Public administration except public order": [
        x
        for x in categories["Public administration"]
        if x != "Estimate!!Total!!Justice, public order, and safety activities"
    ],
    "Public order": ["Estimate!!Total!!Justice, public order, and safety activities"],
    "Technology": categories["Information"]["Technology"],
    "Information except technology": categories["Information"][
        "Information except technology"
    ],
    "Other": {
        #
        "Professional and business services": {
            "Professional and technical services": [
                "Estimate!!Total!!Legal services",
                "Estimate!!Total!!Accounting, tax preparation, bookkeeping, and payroll services",
                "Estimate!!Total!!Architectural, engineering, and related services",
                "Estimate!!Total!!Specialized design services",
                "Estimate!!Total!!Computer systems design and related services",
                "Estimate!!Total!!Management, scientific, and technical consulting services",
                "Estimate!!Total!!Scientific research and development services",
                "Estimate!!Total!!Advertising, public relations, and related services",
                "Estimate!!Total!!Veterinary services",
                "Estimate!!Total!!Other professional, scientific, and technical services",
            ],
            "Management of companies and enterprises": [
                "Estimate!!Total!!Management of companies and enterprises",
            ],
            "Administrative and support services": [
                "Estimate!!Total!!Employment services",
                "Estimate!!Total!!Business support services",
                "Estimate!!Total!!Travel arrangements and reservation services",
                "Estimate!!Total!!Investigation and security services",
                "Estimate!!Total!!Services to buildings and dwellings (except cleaning during construction and immediately after construction)",
                "Estimate!!Total!!Landscaping services",
                "Estimate!!Total!!Other administrative and other support services",
            ],
            "Waste management and remediation services": [
                "Estimate!!Total!!Waste management and remediation services",
            ],
        },
        "Other services": {
            "Repair and maintenance": [
                "Estimate!!Total!!Automotive repair and maintenance",
                "Estimate!!Total!!Car washes",
                "Estimate!!Total!!Electronic and precision equipment repair and maintenance",
                "Estimate!!Total!!Commercial and industrial machinery and equipment repair and maintenance",
                "Estimate!!Total!!Personal and household goods repair and maintenance",
            ],
            "Personal and laundry services": [
                "Estimate!!Total!!Barber shops",
                "Estimate!!Total!!Beauty salons",
                "Estimate!!Total!!Nail salons and other personal care services",
                "Estimate!!Total!!Drycleaning and laundry services",
                "Estimate!!Total!!Funeral homes, and cemeteries and crematories",
                "Estimate!!Total!!Other personal services",
            ],
            "Membership associations and organizations": [
                "Estimate!!Total!!Religious organizations",
                "Estimate!!Total!!Civic, social, advocacy organizations, and grantmaking and giving services",
                "Estimate!!Total!!Labor unions",
                "Estimate!!Total!!Business, professional, political, and similar organizations",
            ],
            "Private households": [
                "Estimate!!Total!!Private households",
            ],
        },
    },
}
