from urbanstats.data.canada.canadian_da_data import CensusTables
from urbanstats.games.quiz_question_metadata import QuizQuestionSkip
from urbanstats.statistics.collections.census_canada_same_as_us import (
    CensusCanadaSameAsUS,
)
from urbanstats.statistics.collections.national_origin_language import (
    NationalOriginLanguageStatistics,
)
from urbanstats.statistics.utils import fractionalize


class CensusCanadaLanguage(CensusCanadaSameAsUS):
    version = 4

    def us_equivalent_fields(self):
        return ["language_english_only", "language_spanish"]

    def census_tables(self) -> CensusTables:
        table_name = (
            "Total - Language spoken most often at home for the total population "
            "excluding institutional residents - 100% data (41)"
        )
        return CensusTables(
            [table_name],
            {
                "language_total": [table_name],
                "language_english_only_canada": [
                    "      English",
                    "    English and non-official language(s)",
                ],
                "language_spanish_canada": [
                    "            Spanish",
                ],
                "language_french_canada": [
                    "      French",
                    "    English and French",
                    "    French and non-official language(s)",
                    "    English, French and non-official language(s)",
                ],
                None: [
                    "  Single responses",
                    "    Official languages",
                    "    Non-official languages",
                    "      Indigenous languages (39)",
                    "        Algonquian languages",
                    "          Blackfoot",
                    "          Cree-Innu languages",
                    "            Atikamekw",
                    "            Cree languages",
                    "              Ililimowin (Moose Cree)",
                    "              Inu Ayimun (Southern East Cree)",
                    "              Iyiyiw-Ayimiwin (Northern East Cree)",
                    "              Nehinawewin (Swampy Cree)",
                    "              Nehiyawewin (Plains Cree)",
                    "              Nihithawiwin (Woods Cree)",
                    "              Cree, n.o.s.",
                    "            Innu (Montagnais)",
                    "            Naskapi",
                    "          Eastern Algonquian languages",
                    "            Mi'kmaq",
                    "            Wolastoqewi (Malecite)",
                    "          Ojibway-Potawatomi languages",
                    "            Anicinabemowin (Algonquin)",
                    "            Oji-Cree",
                    "            Ojibway languages",
                    "              Anishinaabemowin (Chippewa)",
                    "              Daawaamwin (Odawa)",
                    "              Saulteau (Western Ojibway)",
                    "              Ojibway, n.o.s.",
                    "          Algonquian languages, n.i.e.",
                    "        Athabaskan languages",
                    "          Northern Athabaskan languages",
                    "            Dakelh (Carrier)",
                    "            Dane-zaa (Beaver)",
                    "            Dene, n.o.s.",
                    "            Gwich'in",
                    "            Slavey-Hare languages",
                    "              Deh Gah Ghotie Zhatie (South Slavey)",
                    "              Satuotine Yati (North Slavey)",
                    "              Slavey, n.o.s.",
                    "            Tahltan languages",
                    "              Kaska (Nahani)",
                    "              Tahltan",
                    "            Tlicho (Dogrib)",
                    "            Tse'khene (Sekani)",
                    "            Tsilhqot'in (Chilcotin)",
                    "            Tsuu T'ina (Sarsi)",
                    "            Tutchone languages",
                    "              Northern Tutchone",
                    "              Southern Tutchone",
                    "              Tutchone, n.o.s.",
                    "            Wetsuwet'en-Babine",
                    "          Tlingit",
                    "          Athabaskan languages, n.i.e.",
                    "        Haida",
                    "        Inuktut (Inuit) languages",
                    "          Inuinnaqtun (Inuvialuktun)",
                    "            Inuinnaqtun",
                    "            Inuvialuktun",
                    "          Inuktitut",
                    "          Inuktut (Inuit) languages, n.i.e.",
                    "        Iroquoian languages",
                    "          Cayuga",
                    "          Mohawk",
                    "          Oneida",
                    "          Iroquoian languages, n.i.e.",
                    "        Ktunaxa (Kutenai)",
                    "        Michif",
                    "        Salish languages",
                    "          Halkomelem",
                    "          Lillooet",
                    "          Ntlakapamux (Thompson)",
                    "          Secwepemctsin (Shuswap)",
                    "          Squamish",
                    "          Straits",
                    "          Syilx (Okanagan)",
                    "          Salish languages, n.i.e.",
                    "        Siouan languages",
                    "          Assiniboine",
                    "          Dakota",
                    "          Stoney",
                    "          Siouan languages, n.i.e.",
                    "        Tsimshian languages",
                    "          Gitxsan (Gitksan)",
                    "          Nisga'a",
                    "          Tsimshian",
                    "        Wakashan languages",
                    "          Haisla",
                    "          Heiltsuk",
                    "          Kwak'wala (Kwakiutl)",
                    "          Nuu-chah-nulth (Nootka)",
                    "          Wakashan languages, n.i.e.",
                    "        Indigenous languages, n.i.e.",
                    "        Indigenous languages, n.o.s.",
                    "      Non-Indigenous languages",
                    "        Afro-Asiatic languages",
                    "          Berber languages",
                    "            Kabyle",
                    "            Tamazight",
                    "            Berber languages, n.i.e.",
                    "          Chadic languages",
                    "            Hausa",
                    "            Mina",
                    "          Coptic",
                    "          Cushitic languages",
                    "            Bilen",
                    "            Oromo",
                    "            Somali",
                    "            Cushitic languages, n.i.e.",
                    "          Semitic languages",
                    "            Amharic",
                    "            Arabic",
                    "            Aramaic languages",
                    "              Assyrian Neo-Aramaic",
                    "              Chaldean Neo-Aramaic",
                    "              Aramaic, n.o.s.",
                    "            Harari",
                    "            Hebrew",
                    "            Maltese",
                    "            Tigrigna",
                    "            Semitic languages, n.i.e.",
                    "        Austro-Asiatic languages",
                    "          Khmer (Cambodian)",
                    "          Vietnamese",
                    "          Austro-Asiatic languages, n.i.e",
                    "        Austronesian languages",
                    "          Bikol",
                    "          Bisaya, n.o.s.",
                    "          Cebuano",
                    "          Fijian",
                    "          Hiligaynon",
                    "          Ilocano",
                    "          Indonesian",
                    "          Kankanaey",
                    "          Kinaray-a",
                    "          Malagasy languages",
                    "            Merina",
                    "            Malagasy, n.o.s.",
                    "          Malay",
                    "          Pampangan (Kapampangan, Pampango)",
                    "          Pangasinan",
                    "          Tagalog (Pilipino, Filipino)",
                    "          Waray-Waray",
                    "          Austronesian languages, n.i.e.",
                    "        Creole languages",
                    "          Haitian Creole",
                    "          Jamaican English Creole",
                    "          Krio",
                    "          Morisyen",
                    "          Sango",
                    "          Creole, n.o.s.",
                    "          Creole languages, n.i.e.",
                    "        Dravidian languages",
                    "          Kannada",
                    "          Malayalam",
                    "          Tamil",
                    "          Telugu",
                    "          Tulu",
                    "          Dravidian languages, n.i.e.",
                    "        Georgian",
                    "        Hmong-Mien languages",
                    "        Indo-European languages",
                    "          Albanian",
                    "          Armenian",
                    "          Balto-Slavic languages",
                    "            Baltic languages",
                    "              Latvian",
                    "              Lithuanian",
                    "            Slavic languages",
                    "              Belarusian",
                    "              Bulgarian",
                    "              Czech",
                    "              Macedonian",
                    "              Polish",
                    "              Russian",
                    "              Rusyn",
                    "              Serbo-Croatian",
                    "                Bosnian",
                    "                Croatian",
                    "                Serbian",
                    "                Serbo-Croatian, n.i.e.",
                    "              Slovak",
                    "              Slovene (Slovenian)",
                    "              Ukrainian",
                    "              Slavic languages, n.i.e.",
                    "          Celtic languages",
                    "            Irish",
                    "            Scottish Gaelic",
                    "            Welsh",
                    "            Celtic languages, n.i.e.",
                    "          Germanic languages",
                    "            Frisian",
                    "            High German languages",
                    "              German",
                    "              Pennsylvania German",
                    "              Swiss German",
                    "              Yiddish",
                    "            Low Saxon-Low Franconian languages",
                    "              Afrikaans",
                    "              Dutch",
                    "              Low German, n.o.s.",
                    "              Low Saxon",
                    "              Plautdietsch",
                    "              Vlaams (Flemish)",
                    "            Scandinavian languages",
                    "              Danish",
                    "              Icelandic",
                    "              Norwegian",
                    "              Swedish",
                    "            Germanic languages, n.i.e.",
                    "          Greek",
                    "          Indo-Iranian languages",
                    "            Indo-Aryan languages",
                    "              Assamese",
                    "              Bengali",
                    "              Gujarati",
                    "              Hindi",
                    "              Kacchi",
                    "              Kashmiri",
                    "              Konkani",
                    "              Marathi",
                    "              Nepali",
                    "              Oriya languages",
                    "                Odia",
                    "                Oriya, n.o.s.",
                    "              Punjabi (Panjabi)",
                    "              Rohingya",
                    "              Sindhi",
                    "              Sinhala (Sinhalese)",
                    "              Urdu",
                    "              Indo-Aryan languages, n.i.e.",
                    "            Iranian languages",
                    "              Baluchi",
                    "              Kurdish",
                    "              Parsi",
                    "              Pashto",
                    "              Persian languages",
                    "                Dari",
                    "                Iranian Persian",
                    "                Persian (Farsi), n.o.s.",
                    "              Iranian languages, n.i.e.",
                    "            Indo-Iranian languages, n.i.e.",
                    "          Italic (Romance) languages",
                    "            Catalan",
                    "            Italian",
                    "            Portuguese",
                    "            Romanian",
                    "            Italic (Romance) languages, n.i.e.",
                    "          Indo-European languages, n.i.e.",
                    "        Japanese",
                    "        Korean",
                    "        Mongolian",
                    "        Niger-Congo languages",
                    "          Akan (Twi)",
                    "          Bamanankan",
                    "          Edo",
                    "          Éwé",
                    "          Fulah (Pular, Pulaar, Fulfulde)",
                    "          Ga",
                    "          Ganda",
                    "          Gikuyu",
                    "          Igbo",
                    "          Kinyarwanda (Rwanda)",
                    "          Lingala",
                    "          Luba-Kasai",
                    "          Mòoré",
                    "          Mwani",
                    "          Ndebele",
                    "          Rundi (Kirundi)",
                    "          Shona",
                    "          Soninke",
                    "          Sotho-Tswana languages",
                    "          Swahili",
                    "          Wojenaka",
                    "          Wolof",
                    "          Yoruba",
                    "          Niger-Congo languages, n.i.e.",
                    "        Nilo-Saharan languages",
                    "          Dinka",
                    "          Nuer",
                    "          Nilo-Saharan languages, n.i.e.",
                    "          African, n.o.s.",
                    "        Sign languages",
                    "          American Sign Language",
                    "          Quebec Sign Language",
                    "          Sign languages, n.i.e.",
                    "        Sino-Tibetan languages",
                    "          Chinese languages",
                    "            Hakka",
                    "            Mandarin",
                    "            Min Dong",
                    "            Min Nan (Chaochow, Teochow, Fukien, Taiwanese)",
                    "            Wu (Shanghainese)",
                    "            Yue (Cantonese)",
                    "            Chinese, n.o.s.",
                    "            Chinese languages, n.i.e.",
                    "          Tibeto-Burman languages",
                    "            Burmese",
                    "            Kuki-Chin languages",
                    "            Karenic languages",
                    "              S'gaw Karen",
                    "              Karenic languages, n.i.e.",
                    "            Tibetan",
                    "            Tibeto-Burman languages, n.i.e.",
                    "          Sino-Tibetan languages, n.i.e.",
                    "        Tai-Kadai languages",
                    "          Lao",
                    "          Thai",
                    "          Tai-Kadai languages, n.i.e.",
                    "        Turkic languages",
                    "          Azerbaijani",
                    "          Kazakh",
                    "          Turkish",
                    "          Uyghur",
                    "          Uzbek",
                    "          Turkic languages, n.i.e.",
                    "        Uralic languages",
                    "          Estonian",
                    "          Finnish",
                    "          Hungarian",
                    "        Other languages, n.i.e.",
                    "  Multiple responses",
                    "    Multiple non-official languages",
                ],
            },
            "population",
        )

    def us_equivalent(self):
        return NationalOriginLanguageStatistics()

    def name_for_each_statistic(self):
        names = super().name_for_each_statistic()
        names.update(
            {
                "language_french_canada": "French at Home % [StatCan]",
                "language_other_non_french_canada": (
                    "Other (non-French) at Home % [StatCan]"
                ),
            }
        )
        return names

    def varname_for_each_statistic(self):
        varnames = super().varname_for_each_statistic()
        varnames.update(
            {
                "language_french_canada": "french_at_home",
                "language_other_non_french_canada": "other_non_french_at_home",
            }
        )
        return varnames

    def quiz_question_descriptors(self):
        return {
            **super().quiz_question_descriptors(),
            **QuizQuestionSkip.several(
                "language_french_canada",
                "language_other_non_french_canada",
            ),
        }

    def post_process(self, statistic_table):
        statistic_table = statistic_table.copy()
        statistic_table["language_other_non_french_canada"] = (
            statistic_table["language_total"]
            - statistic_table["language_english_only_canada"]
            - statistic_table["language_spanish_canada"]
            - statistic_table["language_french_canada"]
        )
        negative_other = statistic_table["language_other_non_french_canada"][
            statistic_table["language_other_non_french_canada"] < 0
        ]
        assert (
            negative_other.sum() > -1000
        ), f"Negative other language sum is {negative_other.sum()}, which is too high. Check the underlying data for issues."
        statistic_table["language_other_non_french_canada"] = statistic_table[
            "language_other_non_french_canada"
        ].clip(lower=0)
        del statistic_table["language_total"]
        fractionalize(statistic_table, *self.internal_statistic_names_list())
        return statistic_table
