ZERO_POPULATION_UNIVERSES = {
    # 0 population countries. these are not in COUNTRIES
    "Antarctica",
    "Bouvet Island",
    "South Georgia and the South Sandwich Islands",
    "Heard Island and McDonald Islands",
    "British Indian Ocean Territory",
    "United States Minor Outlying Islands",
}

CONTINENTS = [
    "Africa",
    "Asia",
    "Europe",
    "North America",
    "Oceania",
    "South America",
]

COUNTRIES = [
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Argentina",
    "Austria",
    "Australia",
    "Aruba",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Bermuda",
    "Brunei",
    "Bolivia",
    "Brazil",
    "The Bahamas",
    "Bhutan",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos (Keeling) Islands",
    "Democratic Republic of the Congo",
    "Central African Republic",
    "Congo",
    "Switzerland",
    "Ivory Coast",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cape Verde",
    "Christmas Island",
    "Cyprus",
    "Czech Republic",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Micronesia",
    "Faroe Islands",
    "France",
    "Gabon",
    "United Kingdom",
    "Grenada",
    "Georgia",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "The Gambia",
    "Guinea",
    "Equatorial Guinea",
    "Greece",
    "Guatemala",
    "Guinea-Bissau",
    "Guyana",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "Saint Kitts and Nevis",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Montenegro",
    "Madagascar",
    "Marshall Islands",
    "North Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Pitcairn Islands",
    "State of Palestine",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Romania",
    "Serbia",
    "Russia",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Slovenia",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "South Sudan",
    "São Tomé and Príncipe",
    "El Salvador",
    "Syria",
    "Eswatini",
    "Turks and Caicos Islands",
    "Chad",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "East Timor",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Turkey",
    "Trinidad and Tobago",
    "Tuvalu",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "USA",
    "Uruguay",
    "Uzbekistan",
    "Vatican City",
    "Saint Vincent and the Grenadines",
    "Venezuela",
    "British Virgin Islands",
    "Vietnam",
    "Vanuatu",
    "Samoa",
    "Yemen",
    "South Africa",
    "Zambia",
    "Zimbabwe",
]


# The universes (countries, states, and provinces) strictly contained within each
# continent. Countries that straddle a continent boundary (e.g. Russia, Turkey) are
# deliberately not listed under either continent. This is checked against the
# strict containment relationships during the build process, in
# urbanstats.website_data.index.
CONTINENT_TO_SUB_UNIVERSES = {
    "Africa": [
        "Algeria",
        "Angola",
        "Benin",
        "Botswana",
        "Burkina Faso",
        "Burundi",
        "Cameroon",
        "Cape Verde",
        "Central African Republic",
        "Chad",
        "Comoros",
        "Congo",
        "Democratic Republic of the Congo",
        "Djibouti",
        "Equatorial Guinea",
        "Eritrea",
        "Eswatini",
        "Ethiopia",
        "Gabon",
        "Ghana",
        "Guinea",
        "Guinea-Bissau",
        "Ivory Coast",
        "Kenya",
        "Lesotho",
        "Liberia",
        "Libya",
        "Madagascar",
        "Malawi",
        "Mali",
        "Mauritania",
        "Mauritius",
        "Morocco",
        "Mozambique",
        "Namibia",
        "Niger",
        "Nigeria",
        "Rwanda",
        "Saint Helena, Ascension and Tristan da Cunha",
        "Senegal",
        "Seychelles",
        "Sierra Leone",
        "Somalia",
        "South Africa",
        "South Sudan",
        "Sudan",
        "São Tomé and Príncipe",
        "Tanzania",
        "The Gambia",
        "Togo",
        "Tunisia",
        "Uganda",
        "Zambia",
        "Zimbabwe",
    ],
    "Asia": [
        "Afghanistan",
        "Armenia",
        "Azerbaijan",
        "Bahrain",
        "Bangladesh",
        "Bhutan",
        "Brunei",
        "Cambodia",
        "China",
        "Christmas Island",
        "Cocos (Keeling) Islands",
        "Cyprus",
        "East Timor",
        "Georgia",
        "India",
        "Iran",
        "Iraq",
        "Israel",
        "Japan",
        "Jordan",
        "Kazakhstan",
        "Kuwait",
        "Kyrgyzstan",
        "Laos",
        "Lebanon",
        "Malaysia",
        "Maldives",
        "Mongolia",
        "Myanmar",
        "Nepal",
        "North Korea",
        "Oman",
        "Pakistan",
        "Qatar",
        "Saudi Arabia",
        "Singapore",
        "South Korea",
        "Sri Lanka",
        "State of Palestine",
        "Syria",
        "Tajikistan",
        "Thailand",
        "Turkmenistan",
        "United Arab Emirates",
        "Uzbekistan",
        "Vietnam",
        "Yemen",
    ],
    "Europe": [
        "Albania",
        "Andorra",
        "Austria",
        "Belarus",
        "Belgium",
        "Bosnia and Herzegovina",
        "Bulgaria",
        "Croatia",
        "Czech Republic",
        "Denmark",
        "Estonia",
        "Faroe Islands",
        "Finland",
        "Germany",
        "Gibraltar",
        "Greece",
        "Guernsey",
        "Hungary",
        "Iceland",
        "Ireland",
        "Isle of Man",
        "Italy",
        "Jersey",
        "Latvia",
        "Liechtenstein",
        "Lithuania",
        "Luxembourg",
        "Malta",
        "Moldova",
        "Monaco",
        "Montenegro",
        "Netherlands",
        "North Macedonia",
        "Norway",
        "Poland",
        "Portugal",
        "Romania",
        "San Marino",
        "Serbia",
        "Slovakia",
        "Slovenia",
        "Spain",
        "Sweden",
        "Switzerland",
        "Ukraine",
        "United Kingdom",
        "Vatican City",
    ],
    "North America": [
        "Alabama, USA",
        "Alaska, USA",
        "Alberta, Canada",
        "Anguilla",
        "Antigua and Barbuda",
        "Arizona, USA",
        "Arkansas, USA",
        "Barbados",
        "Belize",
        "Bermuda",
        "British Columbia, Canada",
        "British Virgin Islands",
        "California, USA",
        "Canada",
        "Cayman Islands",
        "Colorado, USA",
        "Connecticut, USA",
        "Costa Rica",
        "Cuba",
        "Delaware, USA",
        "District of Columbia, USA",
        "Dominica",
        "Dominican Republic",
        "El Salvador",
        "Florida, USA",
        "Georgia, USA",
        "Greenland",
        "Grenada",
        "Guatemala",
        "Haiti",
        "Honduras",
        "Idaho, USA",
        "Illinois, USA",
        "Indiana, USA",
        "Iowa, USA",
        "Jamaica",
        "Kansas, USA",
        "Kentucky, USA",
        "Louisiana, USA",
        "Maine, USA",
        "Manitoba, Canada",
        "Maryland, USA",
        "Massachusetts, USA",
        "Mexico",
        "Michigan, USA",
        "Minnesota, USA",
        "Mississippi, USA",
        "Missouri, USA",
        "Montana, USA",
        "Montserrat",
        "Nebraska, USA",
        "Nevada, USA",
        "New Brunswick, Canada",
        "New Hampshire, USA",
        "New Jersey, USA",
        "New Mexico, USA",
        "New York, USA",
        "Newfoundland and Labrador, Canada",
        "Nicaragua",
        "North Carolina, USA",
        "North Dakota, USA",
        "Northwest Territories, Canada",
        "Nova Scotia, Canada",
        "Nunavut, Canada",
        "Ohio, USA",
        "Oklahoma, USA",
        "Ontario, Canada",
        "Oregon, USA",
        "Panama",
        "Pennsylvania, USA",
        "Prince Edward Island, Canada",
        "Puerto Rico, USA",
        "Quebec, Canada",
        "Rhode Island, USA",
        "Saint Kitts and Nevis",
        "Saint Lucia",
        "Saint Vincent and the Grenadines",
        "Saskatchewan, Canada",
        "South Carolina, USA",
        "South Dakota, USA",
        "Tennessee, USA",
        "Texas, USA",
        "The Bahamas",
        "Turks and Caicos Islands",
        "US Virgin Islands, USA",
        "USA",
        "Utah, USA",
        "Vermont, USA",
        "Virginia, USA",
        "Washington, USA",
        "West Virginia, USA",
        "Wisconsin, USA",
        "Wyoming, USA",
        "Yukon, Canada",
    ],
    "Oceania": [
        "American Samoa, USA",
        "Australia",
        "Cook Islands",
        "Fiji",
        "Guam, USA",
        "Hawaii, USA",
        "Kiribati",
        "Marshall Islands",
        "Micronesia",
        "Nauru",
        "New Zealand",
        "Niue",
        "Norfolk Island",
        "Northern Mariana Islands, USA",
        "Palau",
        "Papua New Guinea",
        "Pitcairn Islands",
        "Samoa",
        "Solomon Islands",
        "Tokelau",
        "Tonga",
        "Tuvalu",
        "Vanuatu",
    ],
    "South America": [
        "Argentina",
        "Aruba",
        "Bolivia",
        "Brazil",
        "Chile",
        "Colombia",
        "Ecuador",
        "Falkland Islands",
        "Guyana",
        "Paraguay",
        "Peru",
        "Suriname",
        "Trinidad and Tobago",
        "Uruguay",
        "Venezuela",
    ],
}
