import createClient from 'openapi-fetch'

import type { paths } from './google-drive' // generated by openapi-typescript

export function gdriveClient(token: string): typeof client {
    const client = createClient<paths>({ baseUrl: 'https://www.googleapis.com/drive/v3', fetch(input) {
        input.headers.append('Authorization', `Bearer ${token}`)
        return globalThis.fetch(input)
    } })
    return client
}
