import createClient from 'openapi-fetch'

import type { paths } from './urbanstats-persistent-data' // generated by openapi-typescript

const client = createClient<paths>({ baseUrl: 'https://persistent.urbanstats.org' })

const response = await client.POST(
    '/juxtastat/todays_score_for',
    {
        params: { header: { 'X-Secure-Id': '1', 'X-User': '1' } },
        body: { requesters: [], date: 1, quiz_kind: 'juxtastat' },
    },
)

if (response.data) {
    response.data.results.forEach(console.warn)
}
