import createClient from 'openapi-fetch'

import { QuizModel } from '../quiz/quiz'

import { TestUtils } from './TestUtils'
import type { paths } from './urbanstats-persistent-data' // generated by openapi-typescript

// This endpoint answers 401 when Google rejects the access token in the request body, which says
// nothing about whether our own identity headers are good.
const authenticatesSomethingElse = '/juxtastat/associate_email'

export const persistentClient = createClient<paths>({ baseUrl: TestUtils.shared.isTesting ? 'http://localhost:54579' : 'https://persistent.urbanstats.org', async fetch(input) {
    const response = await globalThis.fetch(input)
    // A 401 here means the server holds a different secure id for our persistent id, so someone
    // else is playing as us. Requests without our identity headers can't tell.
    if (input.headers.has('x-secure-id') && new URL(input.url).pathname !== authenticatesSomethingElse) {
        QuizModel.shared.authenticationError.value = response.status === 401
    }
    return response
} })
