/**
 * On the test CI, we want to have multiple test runners in parallel.
 *
 * However, pulling down the densitydb repo to run the tests against each time is expensive.
 *
 * So, our strategy will be to serve the local files generated by generate_site.py,
 * and then any files not generated, we'll proxy the request to a CI proxy that has a copy of densitydb.
 */

import compression from 'compression'
import express from 'express'
import proxy from 'express-http-proxy'
import { z } from 'zod'

import { port } from '../../port'

import { github } from './github-utils'

/**
 * jsdelivr occasionally stalls on a file and answers with a 504 a full minute later, which is
 * long enough on its own to blow a test's time limit. This is a socket inactivity timeout, so a
 * large file that is downloading slowly but steadily isn't affected.
 */
const attemptTimeoutMs = 10_000
const attempts = 3

const handOffToNextAttempt: proxy.ProxyOptions = {
    skipToNextHandlerFilter: proxyRes => (proxyRes.statusCode ?? 500) >= 500,
    proxyErrorHandler: (error, res, next) => { next() },
}

function jsdelivrProxy(sha: string, retryOnFailure: boolean): express.RequestHandler {
    return proxy(`https://cdn.jsdelivr.net`, {
        timeout: attemptTimeoutMs,
        proxyReqPathResolver(req) {
            // We must get by SHA, since if we used branch name jsdelvir would cache the result for 12 hours and we couldn't get new changes from the branch
            return `/gh/densitydb/densitydb.github.io@${sha}${req.path}`
        },
        userResHeaderDecorator(headers, userReq, userRes, proxyReq, proxyRes) {
            const status = proxyRes.statusCode ?? 0
            if (status < 200 || status > 299) {
                // 404 and 429 are not retried, and the frontend turns a missing shard into a
                // "could not find feature" error, so this is where that trail starts
                console.warn(`jsdelivr answered ${status} for ${userReq.path}`)
            }
            const fileExtension = (/\.(.+)$/.exec(userReq.path))?.[1]
            const mimeType = fileExtension ? { html: 'text/html', js: 'text/javascript' }[fileExtension] : undefined
            // eslint-disable-next-line @typescript-eslint/no-unused-vars, no-restricted-syntax -- We're removing the context-security-policy header via destructuring
            const { 'content-security-policy': _, ...filteredHeaders } = headers
            return {
                ...filteredHeaders,
                'content-type': mimeType ?? headers['content-type'],
            }
        },
        // Hand off to the next attempt. The last one has no successor, so it reports what it got.
        ...(retryOnFailure ? handOffToNextAttempt : {}),
    })
}

export async function startProxy(): Promise<void> {
    const { octokit } = await github()

    /**
     * If the user is using a branch that also exists on densitydb, we should use it as well.
     *
     * Otherwise, use `main`
     */
    const targetBranch = z.string().parse(process.env.URBANSTATS_BRANCH_NAME)

    const { data: remoteBranches } = await octokit.rest.repos.listBranches({
        owner: 'densitydb',
        repo: 'densitydb.github.io',
    })

    const branch = remoteBranches.find(({ name }) => name === targetBranch)
        ?? remoteBranches.find(({ name }) => name === 'main')
        ?? (() => { throw new Error('No main branch') })()

    // This is useful for debugging in case the proxy isn't working
    console.warn(`Proxy is using branch ${branch.name} (${branch.commit.sha})`)

    const app = express()

    app.use(compression({ enforceEncoding: 'gzip' }))

    app.use((req, res, next) => {
        const start = Date.now()
        res.on('finish', () => {
            if (res.statusCode >= 400) {
                console.warn(`Proxy served ${res.statusCode} for ${req.path} after ${Date.now() - start}ms`)
            }
        })
        next()
    })

    const handlers: express.RequestHandler[] = []
    for (let attempt = 1; attempt <= attempts; attempt++) {
        if (attempt > 1) {
            handlers.push((req, res, next) => {
                console.warn(`jsdelivr did not serve ${req.path}; starting attempt ${attempt}`)
                next()
            })
        }
        handlers.push(jsdelivrProxy(branch.commit.sha, attempt < attempts))
    }

    app.use(express.static('test/density-db'), ...handlers)

    app.listen(port())
}
