# Automatically create a PR when branches are pushed
name: auto-pr
on: create
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get Commit Message
        id: commit-message
        run: git log -1 --pretty=%B | xargs
      - name: Create Pull Request
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/{owner}/{repo}/pulls
          owner: kavigupta
          repo: urbanstats
          title: ${{ steps.commit-message.outputs.stdout }}
          head: ${{ github.event.ref }}
          base: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.event.ref_type == 'branch'
